set(CPACK_PACKAGE_NAME "robotology-superbuild--dependencies" CACHE STRING "")
set(CPACK_PACKAGE_VENDOR "iCub Tech, Istituto Italiano di Tecnologia (IIT)" CACHE STRING "")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "robotology-superbuild Dependencies Installer" CACHE STRING "")
set(CPACK_PACKAGE_VERSION_MAJOR "0" CACHE STRING "")
set(CPACK_PACKAGE_VERSION_MINOR "1" CACHE STRING "")
set(CPACK_PACKAGE_VERSION_PATCH "0" CACHE STRING "")
set(CPACK_GENERATOR "IFW;ZIP" CACHE STRING "")
set(VCPKG_CPACK_TARGET_PORTS "ipopt-binary;ace;freeglut;gsl;eigen3;ode;libxml2;eigen3;opencv3;matio;sdl1;sdl2;qt5" CACHE STRING "")
set(VCPKG_GIT_REPOSITORY "https://github.com/Microsoft/vcpkg.git" CACHE STRING "")
set(VCPKG_GIT_TAG "2019.08" CACHE STRING "")